"""Interface to GANs, classical and quantum.
"""
from __future__ import annotations
from jax.random import PRNGKeyArray
import jax.tree_util as tree_util
from jaxtyping import Array, Float, PyTree
import equinox as eqx
from abc import abstractmethod, ABCMeta


class GAN(eqx.Module, metaclass=ABCMeta):
    """A generic generative adversarial network.  We provide these methods
    because the intermediate state of a quantum batch GAN cannot be used
    separately while training with generated data.

    The public parameter attributes are used to filter which parameters we take
    gradients with respect to.  (See Equinox's filter_grad).

    Attributes:
      latent_shape: The latent_shape.
      gen_params: PyTree of parameters for the generator.
      dis_params: PyTree of parameters for the discriminator.
    """

    latent_shape: tuple[int] = eqx.static_field(repr=False, compare=False)
    gen_params: PyTree
    dis_params: PyTree

    @abstractmethod
    def random_latent(
        self, key: PRNGKeyArray, batch: int
    ) -> Float[Array, "batch latent"]:
        """Generate a random latent space vector.

        Args:
          key: A JAX PRNG key (determinism).
          batch: The batch size, which will be the number of rows.

        Returns:
          An array of random vector (rows) in the latent space of the GAN.
        """
        raise NotImplementedError

    @abstractmethod
    def train_fake(
        self, latent: Float[Array, "batch latent"]
    ) -> Float[Array, ""]:
        """Generate an image from the given latent space vector, feed it to the
        discriminator, and compute a probability that the discriminator thinks
        the data is real (0.0 -> fake, 1.0 -> real).

        Args:
          latent: An array of vectors in the GAN latent space (generated by
            random_latent).

        Returns:
          Probability from 0 to 1.
        """
        raise NotImplementedError

    @abstractmethod
    def train_real(
        self, features: Float[Array, "batch feature"]
    ) -> Float[Array, ""]:
        """Compute a probability that the discriminator thinks a training
        example is real (0.0 -> fake, 1.0 -> real).

        Args:
          features: An array of feature vectors draw from the training set.
            The minibatch dimension groups examples that return a joint
            probability.

        Returns:
          Probability from 0 to 1.
        """
        raise NotImplementedError

    @abstractmethod
    def generate(
        self, latent: Float[Array, "batch latent"]
    ) -> Float[Array, "batch feature"]:
        """Use a trained network to generate examples.

        Args:
          latent: An array of latent space vectors.

        Returns:
          The generated examples.
        """
        raise NotImplementedError

    def gen_filter(self) -> GAN:
        """Create a pytree filter for the generator parameters.

        Returns:
          The filter.
        """
        return tree_util.tree_map_with_path(lambda p, x: p[0].key == 0, self)

    def dis_filter(self) -> GAN:
        """Create a pytree filter for the discriminator parameters.

        Returns:
          The filter.
        """
        return tree_util.tree_map_with_path(lambda p, x: p[0].key == 1, self)
